name: dockable
version: 0.0.1
description: IDE framework for dart web apps using PolymerDart.
dependencies:
  polymer: any
  polymer_ui_elements: any
transformers:
- polymer:
    entry_points: web/dockable.html
