name: dockable
description: IDE framework for dart web apps using PolymerDart.
version: '0.0.1'
dependencies:
  polymer: any
  polymer_ui_elements: any
transformers:
- polymer:
    entry_points: web/dockable.html
