name: dockable
version: 0.1.10
description: IDE framework for dart web apps using PolymerDart.
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>0.13.0'
transformers:
- polymer:
    entry_points:
    - examples/color_picker/color_picker.html
