name: dockable
version: 0.1.12
description: IDE framework for dart web apps using PolymerDart.
dependencies:
  core_elements: '0.4.0'
  paper_elements: any
  polymer: '>0.13.0'
transformers:
- polymer:
    entry_points:
    - example/color_picker/color_picker.html
