name: dockable
version: 0.0.3
description: IDE framework for dart web apps using PolymerDart.
dependencies:
  polymer: '>0.13.0'
  polymer_ui_elements: any
  paper_elements: any
  core_elements: any
transformers:
- polymer:
    entry_points:
    - web/property_editor/dynamic/property_editor.html
    - web/icon/dynamic/icon.html
