name: dockable
version: 0.1.21
description: IDE framework for dart web apps using PolymerDart.
dependencies:
  core_elements: '0.6.1+2'
  paper_elements: any
  polymer: '>0.13.0'
  sprintf: '>=1.0.7'
transformers:
- polymer:
    entry_points:
    - web/color_picker/color_picker.html
    - web/stage/stage.html
    - web/ordered_list/ordered_list.html
    - web/spinner/spinner.html
    - web/listbox/listbox.html
