name: dockable
version: 0.1.1
description: IDE framework for dart web apps using PolymerDart.
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>0.13.0'
transformers:
- polymer:
    entry_points:
    - web/property_editor/dynamic/property_editor.html
    - web/icon/dynamic/icon.html
